### ISSUE TITLE
Component not found

### ISSUE THREAD

**Issue by teddy-dubal** [kaorun343/vue-photon#1]
Hi , you've got an error at this line

https://github.com/kaorun343/vue-photonkit/blob/master/src/install.js#L22

you named the component List instead of ListGroup.

**Comment by kaorun343** [comment]
Thanks!
I'll fix this until tomorrow.

**Comment by kaorun343** [comment]
done.

**Comment by teddy-dubal** [comment]
Thanks. Good job
